services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  # (Optionnel) Base de données
  db:
    image: mysql:8
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: gabconcoursv5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
